name = "deeds-app"
main = "functions/_worker.js"
compatibility_date = "2023-10-23"

[vars]
DEMO_MODE_ENABLED = "false"
SESSION_SECRET = "7627942201"



[env.demo]
[env.demo.vars]
DEMO_MODE_ENABLED = "true"

[assets]
binding = "ASSETS"
directory = "./public"


[[d1_databases]]
binding = "DEEDS_DB"
database_name = "deeds-app-db"
database_id = "6f28b6d0-bd5c-4e30-9703-a13079d9d44f"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
persist = true
invocation_logs = true
